[package]
name = "sensor_log_api"
version = "0.1.0"
edition = "2021"

[dependencies]
postgres = {version = "0.19", features = ["with-chrono-0_4", "with-time-0_3"]}
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
http-auth-basic = "<1.0"
chrono = { version = "0.4", features = ["serde"] }